In [2]:
!pip install pandas numpy matplotlib scikit-learn

Collecting pandas
  Using cached pandas-3.0.0-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.4.2-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Collecting matplotlib
  Using cached matplotlib-3.10.8-cp313-cp313-win_amd64.whl.metadata (52 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.8.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\investiq\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.61.1-cp313-cp313-win_amd64.whl.metadata (116 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.4.9-cp313-cp313-win_amd64.whl.metadata (6.4 kB)
Requirement already satisfied: packaging>=20.0 in e:\investiq\.venv\lib\site-packages (from matplotlib) (26.0)
Collecting pillow>=8 (from matplotlib)
  Using cached pillow-12.1.0-cp313-cp313-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.0-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: six>=1.5 in e:\investiq\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.0-cp313-cp313-win_amd64.whl (9.7 MB)
Downloading numpy-2.4.2-cp313-cp313-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 1.3 MB/s eta 0:00:10
   -- ------------------------------------- 0.8/12.3 MB 1.3 MB/s eta 0:00:09
   --- ------------------------------------ 1.0/12.3 MB 1.3 MB/s eta 0:00:09
   ---- ----------------------------------- 1.3/12.3 MB 1.3 MB/s eta 0:00:09
   ----- ---------------------------------- 1.6/12.3 MB 1.3 MB/s eta 0:00:09
   ----- ---------------------------------- 1.8/12.3 MB 1.3 MB/s eta 0:00:09
   ------ --------------------------------- 2.1/12.3 MB 1.3 MB/s eta 0:00:08
   ------- -------------------------------- 2.4/12.3 MB 1.3 MB/s eta 0:00:08
   -------- ------------------------------- 2.6/12.3 MB 1.3 MB/s eta 0:00:08
   --------- ------------------------------ 2.9/12.3 MB 1.3 MB/s eta 0:00:08
   ---------- ----------------------------- 3.1/12.3 MB 1.3 MB/s eta 0:00:08
   ----------- ---------------------------- 3.4/12.3 MB 1.3 MB/s eta 0:00:07
   ----------- ---------------------------- 3.7/12.3 MB 1.3 MB/s eta 0:00:07
   ------------ --------------------------- 3.9/12.3 MB 1.3 MB/s eta 0:00:07
   ------------- -------------------------- 4.2/12.3 MB 1.3 MB/s eta 0:00:07
   -------------- ------------------------- 4.5/12.3 MB 1.3 MB/s eta 0:00:07
   --------------- ------------------------ 4.7/12.3 MB 1.3 MB/s eta 0:00:06
   ---------------- ----------------------- 5.0/12.3 MB 1.3 MB/s eta 0:00:06
   ----------------- ---------------------- 5.2/12.3 MB 1.3 MB/s eta 0:00:06
   ----------------- ---------------------- 5.5/12.3 MB 1.3 MB/s eta 0:00:06
   ------------------ --------------------- 5.8/12.3 MB 1.3 MB/s eta 0:00:06
   ------------------- -------------------- 6.0/12.3 MB 1.3 MB/s eta 0:00:05
   -------------------- ------------------- 6.3/12.3 MB 1.3 MB/s eta 0:00:05
   --------------------- ------------------ 6.6/12.3 MB 1.3 MB/s eta 0:00:05
   ---------------------- ----------------- 6.8/12.3 MB 1.3 MB/s eta 0:00:05
   ---------------------- ----------------- 7.1/12.3 MB 1.3 MB/s eta 0:00:05
   ------------------------ --------------- 7.6/12.3 MB 1.3 MB/s eta 0:00:04
   ------------------------- -------------- 7.9/12.3 MB 1.3 MB/s eta 0:00:04
   -------------------------- ------------- 8.1/12.3 MB 1.3 MB/s eta 0:00:04
   --------------------------- ------------ 8.4/12.3 MB 1.3 MB/s eta 0:00:04
   ---------------------------- ----------- 8.7/12.3 MB 1.3 MB/s eta 0:00:03
   ---------------------------- ----------- 8.9/12.3 MB 1.3 MB/s eta 0:00:03
   ----------------------------- ---------- 9.2/12.3 MB 1.3 MB/s eta 0:00:03
   ------------------------------ --------- 9.4/12.3 MB 1.3 MB/s eta 0:00:03
   ------------------------------- -------- 9.7/12.3 MB 1.3 MB/s eta 0:00:03
   -------------------------------- ------- 10.0/12.3 MB 1.3 MB/s eta 0:00:02
   --------------------------------- ------ 10.2/12.3 MB 1.3 MB/s eta 0:00:02
   ---------------------------------- ----- 10.5/12.3 MB 1.3 MB/s eta 0:00:02
   ---------------------------------- ----- 10.7/12.3 MB 1.3 MB/s eta 0:00:02
   ----------------------------------- ---- 11.0/12.3 MB 1.3 MB/s eta 0:00:02
   ------------------------------------ --- 11.3/12.3 MB 1.3 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.3 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 11.8/12.3 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 1.3 MB/s  0:00:09
Using cached matplotlib-3.10.8-cp313-cp313-win_amd64.whl (8.1 MB)
Using cached scikit_learn-1.8.0-cp313-cp313-win_amd64.whl (8.0 MB)
Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.61.1-cp313-cp313-win_amd64.whl (2.3 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached kiwisolver-1.4.9-cp313-cp313-win_amd64.whl (73 kB)
Using cached pillow-12.1.0-cp313-cp313-win_amd64.whl (7.0 MB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Using cached scipy-1.17.0-cp313-cp313-win_amd64.whl (36.3 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, threadpoolctl, pyparsing, pillow, numpy, kiwisolver, joblib, fonttools, cycler, scipy, pandas, contourpy, scikit-learn, matplotlib

   ----------------------------------------  0/14 [tzdata]
   ----- ----------------------------------  2/14 [pyparsing]
   -------- -------------------------------  3/14 [pillow]
   -------- -------------------------------  3/14 [pillow]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------------- ----------------------  6/14 [joblib]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ------------------------------- -------- 11/14 [contourpy]
   ---------------------------------- ----- 12/14 [scikit-learn]
   ---------------------------------- ----- 12/14 [scikit-learn]
   ---------------------------------- ----- 12/14 [scikit-learn]
   ---------------------------------- ----- 12/14 [scikit-learn]
   ---------------------------------- ----- 12/14 [scikit-learn]
   ---------------------------------- ----- 12/14 [scikit-learn]
   ---------------------------------- ----- 12/14 [scikit-learn]
   ---------------------------------- ----- 12/14 [scikit-learn]
   ---------------------------------- ----- 12/14 [scikit-learn]
   ---------------------------------- ----- 12/14 [scikit-learn]
   ---------------------------------- ----- 12/14 [scikit-learn]
   ---------------------------------- ----- 12/14 [scikit-learn]
   ---------------------------------- ----- 12/14 [scikit-learn]
   ---------------------------------- ----- 12/14 [scikit-learn]
   ---------------------------------- ----- 12/14 [scikit-learn]
   ------------------------------------- -- 13/14 [matplotlib]
   ------------------------------------- -- 13/14 [matplotlib]
   ------------------------------------- -- 13/14 [matplotlib]
   ------------------------------------- -- 13/14 [matplotlib]
   ------------------------------------- -- 13/14 [matplotlib]
   ------------------------------------- -- 13/14 [matplotlib]
   ------------------------------------- -- 13/14 [matplotlib]
   ------------------------------------- -- 13/14 [matplotlib]
   ------------------------------------- -- 13/14 [matplotlib]
   ------------------------------------- -- 13/14 [matplotlib]
   ---------------------------------------- 14/14 [matplotlib]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.61.1 joblib-1.5.3 kiwisolver-1.4.9 matplotlib-3.10.8 numpy-2.4.2 pandas-3.0.0 pillow-12.1.0 pyparsing-3.3.2 scikit-learn-1.8.0 scipy-1.17.0 threadpoolctl-3.6.0 tzdata-2025.3

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
import pandas as pd

df = pd.read_csv("E:/data.csv")
df.head()

  Company        Date Close/Last    Volume     Open       High      Low
0    AAPL  07/17/2023    $193.99  50520160  $191.90    $194.32  $191.81
1    AAPL  07/14/2023    $190.69  41616240  $190.23  $191.1799  $189.63
2    AAPL  07/13/2023    $190.54  41342340  $190.50    $191.19  $189.78
3    AAPL  07-12-2023    $189.77  60750250  $189.68    $191.70  $188.47
4    AAPL  07-11-2023    $188.08  46638120  $189.16    $189.30  $186.60

In [5]:
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 25160 entries, 0 to 25159
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Company     25160 non-null  str
 1   Date        25160 non-null  str
 2   Close/Last  25160 non-null  str
 3   Volume      25160 non-null  int64
 4   Open        25160 non-null  str
 5   High        25160 non-null  str
 6   Low         25160 non-null  str
dtypes: int64(1), str(6)
memory usage: 1.3 MB

Company       0
Date          0
Close/Last    0
Volume        0
Open          0
High          0
Low           0
dtype: int64

In [27]:
df=df.dropna()
df.head()

  Company        Date Close/Last    Volume     Open       High      Low
0    AAPL  07/17/2023    $193.99  50520160  $191.90    $194.32  $191.81
1    AAPL  07/14/2023    $190.69  41616240  $190.23  $191.1799  $189.63
2    AAPL  07/13/2023    $190.54  41342340  $190.50    $191.19  $189.78
3    AAPL  07-12-2023    $189.77  60750250  $189.68    $191.70  $188.47
4    AAPL  07-11-2023    $188.08  46638120  $189.16    $189.30  $186.60